version: 2.1

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          heroku login
          heroku git:clone -a juno-core 
          cd juno-core
          heroku git:remote -a juno-core
          git push heroku main
      - heroku/deploy-via-git


workflows:
  build:
    jobs:
      - node/run:
          pkg-manager: yarn
          yarn-run: lint:prettier
  heroku_deploy:
    jobs:
      - deploy

orbs:
  node: circleci/node@5.0.0
  heroku: circleci/heroku@1.2.6
